### ISSUE TITLE
modus-vivendi colors not exported

### ISSUE THREAD

**Issue by lccambiaghi** [DogLooksGood/org-html-themify#2]
Hi, I absolutely love your package! So simple and works so well!

I have set light and dark themes to the modus-themes.
I use a variation of the colour palettes, here are the two lists: https://github.com/lccambiaghi/vanilla-emacs/blob/9eaafca081c0e97cbe48f1e8e0d29c4ac67efbce/init.el#L330 

When I export the org file to HTML (https://lccambiaghi.github.io/vanilla-emacs/readme.html), the dark theme override gets correctly exported while the light one fails to do so: https://github.com/lccambiaghi/vanilla-emacs/blob/9eaafca081c0e97cbe48f1e8e0d29c4ac67efbce/readme.html#L144

Could you help me debug what went wrong? Thank you!

**Comment by DogLooksGood** [comment]
Hi, 

Basically org-html-themify is using colors from font-lock-*-face(for example, font-lock-string-face). 
I'm not familiar with customization with modus themes. But it looks like you're not override the font-lock-*-faces?

**Comment by lccambiaghi** [comment]
Re-exporting the document again when having the light theme active worked.. 

Maybe it has something to do with my function to load the theme at the right theme of the day? I will do some more testing.

Thanks anyway!!
